export enum RoleEnum{
  CREATE = "CREATE",
  UPDATE = "UPDATE",
  READ = "READ",
  DELETE = "DELETE",
  SEARCH_MACHINES = "SEARCH_MACHINES",
  START_MACHINES = "START_MACHINES",
  STOP_MACHINES = "STOP_MACHINES",
  RESTART_MACHINES = "RESTART_MACHINES",
  CREATE_MACHINES = "CREATE_MACHINES",
  DESTROY_MACHINES = "DESTROY_MACHINES"
}
